### ISSUE TITLE
Search defaults to undefined

### ISSUE THREAD

**Issue by FatalblazeAM** [TimIsOverpowered/Caedrel-Site#1]
When I try to type anything into the search bar and press the return key, the listed VODs do not changed and the search bar reads "undefined"
![image](https://github.com/TimIsOverpowered/Caedrel-Site/assets/106050229/06ebba8b-3e8b-4882-8891-67b52f49dd48)

**Comment by TimIsOverpowered** [comment]
Replaced with filters
