### ISSUE TITLE
Can't get back to video-overview

### ISSUE THREAD

**Issue by Ole-rgb** [TimIsOverpowered/Caedrel-Site#2]
When I click on a video i can't find a back-button that takes me back to the overview 

<img width="1920" alt="Screenshot 2024-02-09 at 13 47 53" src="https://github.com/TimIsOverpowered/Caedrel-Site/assets/77236934/80cfbe90-1c60-4f72-ba12-9ad42d70187d">

**Comment by TimIsOverpowered** [comment]
Have you tried the back button on the browser?

**Comment by Ole-rgb** [comment]
That is working, just thought it might have been nice to have a little back button.

**Comment by TimIsOverpowered** [comment]
I don't think it makes sense to add a custom back button because it would be redundant and add unnecessary space.
